# CMake generated Testfile for 
# Source directory: D:/OpenSource/CASL/core/tests
# Build directory: D:/OpenSource/CASL/build-core/core/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_assembler]=] "D:/OpenSource/CASL/build-core/core/tests/Debug/test_assembler.exe")
  set_tests_properties([=[test_assembler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_assembler]=] "D:/OpenSource/CASL/build-core/core/tests/Release/test_assembler.exe")
  set_tests_properties([=[test_assembler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_assembler]=] "D:/OpenSource/CASL/build-core/core/tests/MinSizeRel/test_assembler.exe")
  set_tests_properties([=[test_assembler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_assembler]=] "D:/OpenSource/CASL/build-core/core/tests/RelWithDebInfo/test_assembler.exe")
  set_tests_properties([=[test_assembler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_assembler]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_machine]=] "D:/OpenSource/CASL/build-core/core/tests/Debug/test_machine.exe")
  set_tests_properties([=[test_machine]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_machine]=] "D:/OpenSource/CASL/build-core/core/tests/Release/test_machine.exe")
  set_tests_properties([=[test_machine]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_machine]=] "D:/OpenSource/CASL/build-core/core/tests/MinSizeRel/test_machine.exe")
  set_tests_properties([=[test_machine]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_machine]=] "D:/OpenSource/CASL/build-core/core/tests/RelWithDebInfo/test_machine.exe")
  set_tests_properties([=[test_machine]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/OpenSource/CASL/core/tests/CMakeLists.txt;9;add_test;D:/OpenSource/CASL/core/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_machine]=] NOT_AVAILABLE)
endif()
